# Generated by Django 4.2.7 on 2023-12-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserBankAccount',
        ),
    ]
